version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      internal_network:
        ipv4_address: 192.168.1.77

  backend:
    build:
      context: .
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      internal_network:
        ipv4_address: 192.168.1.100
    ports:
      - "8080:8080"

networks:
  internal_network:
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
